# This is a basic workflow to help you get started with Actions

name: test_hexlet-ci-app

# Controls when the workflow will run
on: push
jobs:
  build: # имя взято для примера
    runs-on: ubuntu-latest

    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v2
      # Устанавливаем Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm
      - run: make setup
      - run: make test
      - run: make lint
